# Generated by Django 2.2 on 2019-05-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190513_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
